person:
  username: Zhangsan
  boss: true
  birth: 2019/12/12
  age: 18
  pet:
      name: tomcat
      weight: 23.4
  interests:
    - 篮球
    - 足球
  animal:
      - jerry
      - mario
  score:
      english:
        first: 30
        second: 40
        third: 50
      math: [ 131,140,148 ]
      chinese: { first: 128,second: 136 }
  salarys: [ 3999,4999.98,5999.99 ]
  allPets:
      sick:
        - { name: tom }
        - { name: jerry,weight: 47 }
      health: [ { name: mario,weight: 47 } ]